### ISSUE TITLE
Email notification service

### ISSUE THREAD

**Issue by NickChapman** [juan-t0rres/mock-interview-app#29]
We should build some basic infra to support emailing users about various things. For our MVP, this means emailing users that they have been matched for an interview.

**Comment by alexschles** [comment]
This is complete. An email is sent to the interview request or and acceptor (without them being able to see each other’s email addresses) with interview details. 

For post-MVP work, I’ll try to make the email fancier (with HTML and/or in the form of a PDF attachment, perhaps with clickable links for the environment and hangouts urls).
